name: Debug Categories

on:
workflow_dispatch:

jobs:
show:
runs-on: ubuntu-latest
steps:
- name: Create query file
run: |
cat << 'EOF' > query.graphql
query {
repository(owner: "prabhatre", name: "prabhatre.github.io") {
discussionCategories(first: 20) {
nodes {
id
name
}
}
}
}
EOF

```
  - name: Run query
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      gh api graphql -f query=@query.graphql
```
